import { createContext, useContext, useState, useEffect } from 'react';
import { ethers } from 'ethers';

// Import ABIs and Addresses automatically generated by the deploy script
import addresses from '../../contracts/contract-addresses.json';
import EcoNFTArtifact from '../../contracts/EcoNFT.json';
import EcoTokenArtifact from '../../contracts/EcoToken.json';
import EcoMarketplaceArtifact from '../../contracts/EcoMarketplace.json';

const Web3Context = createContext();

export const useWeb3 = () => useContext(Web3Context);

export const Web3Provider = ({ children }) => {
    const [account, setAccount] = useState(null);
    const [contracts, setContracts] = useState({
        ecoNFT: null,
        ecoToken: null,
        ecoMarketplace: null
    });
    const [isOwner, setIsOwner] = useState(false);
    const [loading, setLoading] = useState(true);

    const initializeWeb3 = async () => {
        if (window.ethereum) {
            try {
                const provider = new ethers.BrowserProvider(window.ethereum);
                
                // --- DEBUGGING & ROBUST NETWORK CHECK ---
                const network = await provider.getNetwork();
                const chainId = network.chainId; // BigInt in ethers v6
                const chainIdStr = chainId.toString();

                // Get raw chainId from MetaMask for extra debugging
                const rawChainId = await window.ethereum.request({ method: 'eth_chainId' });
                
                console.log("--- WEB3 CONNECT DEBUG ---");
                console.log("Ethers Network Object:", network);
                console.log("Ethers Chain ID (String):", chainIdStr);
                console.log("MetaMask Raw Chain ID:", rawChainId); // Likely hex, e.g., 0x7a69
                
                // Robust Check: 31337 (Hardhat default) or 1337 (Localhost)
                // We REMOVED Chain ID 1 because our local node is definitely running on 31337.
                // If you see Chain ID 1, you are likely connected to Real Mainnet.
                const allowedChains = ['31337', '1337'];
                
                if (!allowedChains.includes(chainIdStr)) {
                     console.error(`Network Mismatch! Connected to ${chainIdStr}, expected 31337 or 1337.`);
                     
                     try {
                        // Attempt to switch to Localhost 8545 (Chain ID 31337)
                        await window.ethereum.request({
                            method: 'wallet_switchEthereumChain',
                            params: [{ chainId: '0x7A69' }], // 31337 in hex
                        });
                        return;
                     } catch (switchError) {
                        // This error code indicates that the chain has not been added to MetaMask.
                        if (switchError.code === 4902) {
                            try {
                                await window.ethereum.request({
                                    method: 'wallet_addEthereumChain',
                                    params: [
                                        {
                                            chainId: '0x7A69',
                                            chainName: 'Hardhat Localhost',
                                            rpcUrls: ['http://127.0.0.1:8545'],
                                            nativeCurrency: { name: 'ETH', symbol: 'ETH', decimals: 18 },
                                        },
                                    ],
                                });
                            } catch (addError) {
                                console.error("Failed to add network:", addError);
                            }
                        } else {
                            alert(`Wrong Network Detected.\n\nDetected Chain ID: ${chainIdStr}\nExpected: 31337 (Localhost)\n\nPlease switch MetaMask to 'Localhost 8545'.`);
                        }
                     }
                     setLoading(false);
                     return;
                }
                console.log("Network check passed!");
                // ----------------------------------------

                const signer = await provider.getSigner();
                const userAddress = await signer.getAddress();
                setAccount(userAddress);

                console.log("Contract Addresses:", addresses);

                // Verify code exists at address BEFORE initializing contracts
                const code = await provider.getCode(addresses.EcoNFT);
                if (code === "0x") {
                    const blockNumber = await provider.getBlockNumber();
                    console.error("EcoNFT contract not found at address:", addresses.EcoNFT);
                    console.error("Current Block Number:", blockNumber);
                    alert(`Contract not found on this network (Block: ${blockNumber}).\n\nPossible Causes:\n1. MetaMask has cached an old state -> Clear Activity Data.\n2. You are connected to the wrong node -> Check RPC URL.\n3. Contract address assumes a previous deployment.`);
                    setLoading(false);
                    return;
                }

                // Initialize Contracts
                const ecoNFT = new ethers.Contract(addresses.EcoNFT, EcoNFTArtifact.abi, signer);
                const ecoToken = new ethers.Contract(addresses.EcoToken, EcoTokenArtifact.abi, signer);
                const ecoMarketplace = new ethers.Contract(addresses.EcoMarketplace, EcoMarketplaceArtifact.abi, signer);

                setContracts({ ecoNFT, ecoToken, ecoMarketplace });

                // Check if the connected user is the owner of the NFT contract
                try {
                    const owner = await ecoNFT.owner();
                    setIsOwner(owner.toLowerCase() === userAddress.toLowerCase());
                } catch (error) {
                    console.error("Error fetching owner:", error);
                    setIsOwner(false);
                }

            } catch (error) {
                console.error("Failed to connect wallet:", error);
            }
        }
        setLoading(false);
    };

    useEffect(() => {
        // Attempt to connect on load if permission was already granted
        if (window.ethereum && window.ethereum.selectedAddress) {
             initializeWeb3();
        } else {
            setLoading(false);
        }
        
        // Listen for account changes
        if(window.ethereum) {
            window.ethereum.on('accountsChanged', (accounts) => {
                if(accounts.length > 0) {
                    initializeWeb3();
                } else {
                    setAccount(null);
                    setIsOwner(false);
                }
            });
        }

        return () => {
             if(window.ethereum) window.ethereum.removeAllListeners();
        }
    }, []);

    const connectWallet = async () => {
        if (!window.ethereum) {
            alert("Please install MetaMask!");
            return;
        }
        await window.ethereum.request({ method: 'eth_requestAccounts' });
        await initializeWeb3();
    };

    return (
        <Web3Context.Provider value={{ account, contracts, isOwner, connectWallet, loading }}>
            {children}
        </Web3Context.Provider>
    );
};
